#!/usr/bin/env bash

set -euo pipefail

TOOL_NAME="hcloud-upload-image"
REPO_URL="https://github.com/apricote/hcloud-upload-image"
TAG_PREFIX="v"

dl_link() {
    RELEASE_BASE_URL="$REPO_URL/releases/download/$TAG_PREFIX$ASDF_INSTALL_VERSION"
    DL_FILE="${TOOL_NAME}_$(uname -s)_$(uname -m).tar.gz"

    URL="$RELEASE_BASE_URL/$DL_FILE"

    printf "%s" "$URL"
}

say() {
    printf "[asdf-$TOOL_NAME]: %s\n" "$*"
}

fail() {
    say "$*" >&2
    exit 1
}

sort_semver() {
    sort -t. -k 1,1n -k 2,2n -k 3,3n
}

list_github_semver_tags() {
    git ls-remote --tags --refs "$REPO_URL" \
        | cut -d/ -f3- \
        | sed "s/^v//" \
        | grep -oE '^[0-9]+\.[0-9]+\.[0-9]+$' \
        | uniq
}

is_valid() {
    url="$1"
    if which curl > /dev/null; then
        curl -s --fail "$url"
    elif which wget > /dev/null; then
        wget -q --spider "$url" &> /dev/null
    else
        fail "Error: Neither curl nor wget is available."
    fi
}

download() {
    url="$1"

    if which curl > /dev/null; then
        curl -fsSL ${GITHUB_API_TOKEN:+-H "Authorization: token $GITHUB_API_TOKEN"} "$url"
    elif which wget > /dev/null; then
        wget -q -O- ${GITHUB_API_TOKEN:+--header="Authorization: token $GITHUB_API_TOKEN"} "$url"
    else
        fail "Error: Neither curl nor wget is available."
    fi
}
